### Eigen value Calculator

In [1]:
import numpy as np
from numpy.linalg import eig

a = np.array([[8,0,7,9,2], 
              [24,2,18,17,2]])
cov_a = np.cov(a,ddof=0)
cov_a

array([[12.56, 29.48],
       [29.48, 80.64]])

In [2]:
import numpy as np
from numpy.linalg import eig

a = np.array([[17,11,11], 
              [17,9,8],[12,13,19]])
cov_a = np.cov(a,ddof=0)
cov_a

array([[ 8.        , 11.33333333, -5.33333333],
       [11.33333333, 16.22222222, -8.55555556],
       [-5.33333333, -8.55555556,  9.55555556]])

In [3]:
np.linalg.det(cov_a)

1.0588334856683206e-13

In [4]:
np.var(a[0])

8.0

In [5]:
np.cov(a)

array([[ 12.        ,  17.        ,  -8.        ],
       [ 17.        ,  24.33333333, -12.83333333],
       [ -8.        , -12.83333333,  14.33333333]])

In [6]:
# col means
print(np.mean(a[0]))
print(np.mean(a[1]))

13.0
11.333333333333334


In [7]:
w,v=eig(cov_a)
print('E-value:', w)
print('E-vectors')
print(v)

E-value: [2.93020440e+01 1.33315847e-15 4.47573378e+00]
E-vectors
[[-0.50440367 -0.78983231  0.34891526]
 [-0.73425447  0.60497794  0.30801309]
 [ 0.45436473  0.10082966  0.885091  ]]


In [8]:
# PCA projection
# Work in progress for the pc1 coordinates
pc1 = a.T@v[0]
pc1

array([-17.81502853,  -8.12103276,  -5.23770888])

In [9]:
import statistics as st
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import math
import sympy as sp
from sympy import *

X=[69, 74, 68, 73, 72, 87, 66, 70, 74, 68, 72, 89, 74, 67, 66, 71, 72, 75, 76, 78, 65]
Y = [163, 175, 165, 135, 172, 160, 115, 157, 200, 132, 140, 165, 285, 92, 142, 150, 165, 182, 212, 220, 134]
mean_X=sum(X)/len(X)
median_X=np.median(X)
mode_X=st.mode(np.array(X))
print("mean of X is",mean_X)
print("median of X is ",median_X)
print("mode of X is ",mode_X)

var=0
mean_Y=np.mean(Y)
print("Mean of Y is ",mean_Y)
for i in Y:
    var+=(i-mean_Y)*(i-mean_Y)
Var_Y=var/21
print("Variance of Y is ",Var_Y)
print("Covariance",np.cov(np.array([X,Y]),ddof=0))

ModuleNotFoundError: No module named 'scipy'