In [ ]:
import numpy as np
import scipy.stats

In [ ]:
# x = [25,20,14,24,19,12,44,17,15,18]
x = [25.1,20.7,24.3,19.4,31.9,15.0]
# x = [17,18,19]

In [ ]:
mean = np.mean(x)
sigma = np.std(x)
print("Mean : ", mean)
print("Sigma : ", sigma)


Mean :  22.733333333333334
Sigma :  5.2778362569859585


In [ ]:
# Given a value x_test normal distribution value is 
x_test = 23.2
scipy.stats.norm(mean, sigma).pdf(x_test)

0.07529332437944582

In [ ]:
0.07529332437944582*0.6

0.04517599462766749

In [ ]:
######Bayes Theorem Below PLease Ignore If not asked

In [ ]:
mu = np.matrix([[5.01,3.42], [6.26, 2.87]])

cov = np.array([[[1,0],[0,1]], [[1,0],[0,1]],[[1,0],[0,1]]], dtype='float')

cov = np.array([[[0.122,0.098],[0.098,0.142]], [[0.435,0.121],[0.121,0.110]]], dtype='float')
cov

array([[[0.122, 0.098],
        [0.098, 0.142]],

       [[0.435, 0.121],
        [0.121, 0.11 ]]])

In [ ]:
from sklearn import datasets
from sklearn.decomposition import PCA

# import some data to play with
iris = datasets.load_iris()
x = iris.data[:, :2]  # we only take the first two features.
y = iris.target

In [ ]:

def bv_normal(x, mu, cov):
    
    # Exponential Term
    exp_ = np.matrix(x-mu)*np.linalg.inv(cov)*np.matrix(x-mu).T
    # Coefficient term
    coeff = 1/(np.power(2*np.pi,d/2) *np.sqrt(np.linalg.det(cov)) )
    
    #Calculate f(x_i)
    f_xi = coeff * np.exp(- exp_ / 2)
    
    return f_xi.item()

In [ ]:
d = 2

nc = 2

n = x.shape[0]
P_c = np.array([1/3,10/15])
x= np.array([[6.75,4.25]])
x

array([[6.75, 4.25]])

In [ ]:
X = 

In [ ]:
mu[0]

matrix([[5.01, 3.42]])

In [ ]:
bv_normal(x, mu[0], cov[0])*P_c[0] 

1.9324661025622262e-07

In [ ]:
bv_normal(x, mu[1], cov[1])*P_c[1] 

1.7602659472522413e-05

In [ ]:
P_c[0] 

0.3333333333333333

In [ ]:
import matplotlib.pyplot as plt
from scipy.stats import multivariate_normal
#x = (1,1,1)
#y = multivariate_normal.pdf(x, mean=2.5, cov=0.5);
