In [1]:
import numpy as np
from scipy import stats
import statistics
from matplotlib import pyplot as plt

## Find Mean Median, mode

In [2]:
x = np.array((69, 74, 68, 73, 72, 87, 66, 70, 74, 68, 72, 89, 74, 67, 66, 71, 72, 75, 76, 78, 65))
y = np.array((163, 175, 165, 135, 172, 160, 115, 157, 200, 132, 140, 165, 285, 92, 142, 150, 165, 182, 212, 220, 134))

print(x.mean())
print(np.median(x))
print(stats.mode(x))

# Uses (n-1) as denominator
print(statistics.variance(x))
# Uses (n) as denominator
print(np.var(x))

# print(sum([np.power(i-np.mean(x),2) for i in x]))
# print(770.66/21)

72.66666666666667
72.0
ModeResult(mode=array([72]), count=array([3]))
38
36.698412698412696


## Covariance & Correlation calculation

In [3]:
# Variance of X using n denominator
var_x = sum([np.power(i-np.mean(x),2) for i in x]) / len(x)
print("Variance X (n) : ",var_x)

# Variance of Y using n denominator
var_y = sum([np.power(i-np.mean(y),2) for i in y]) / len(y)
print("Variance Y (n) : ",var_y)

# Covariance using n denominator
covar = sum([(x[i] - x.mean())*(y[i] - y.mean()) for i in range(len(x))]) / len(y)
print("Covariance (n) : ", covar)

# Correlation between X and Y (n in denominator)
corr = covar/np.sqrt(var_x * var_y)
print("Correlation : ",corr)

Variance X (n) :  36.698412698412696
Variance Y (n) :  1597.4875283446713
Covariance (n) :  94.55555555555556
Correlation :  0.39052125143988037


In [4]:
# PCA

In [5]:
# Add data
data = np.matrix([[8, 24],[0 ,2],[7, 18],[9 ,17],[2, 2]])
print("\nData : \n", data)

n = data.shape[0]

# Mean of data 
mean = data.mean(axis = 0)
print("\nMean : \n", mean )

# Covariance of data 
covar = np.cov(data.T)*(n-1)/n
print("\nCovariance : \n", covar)

# Mean subtracted data
centered_data = data - data.mean(axis = 0)
print("\nMean suubtracted data : \n", centered_data)

# Eigen Decomposition
eig_val, eig_vec = np.linalg.eig(covar)
print("\nEigen values : \n",eig_val)
print("\nEigen vectors : \n",eig_vec.T)

# Transformed_data - CHECK before using
# Centered in new coordinate system
new_data_centered = centered_data * np.matrix(eig_vec)[:,-1]
print("\nNew data points (centered) : \n", new_data_centered)

# Uncentered in new coordinate system
new_data = data * np.matrix(eig_vec)[:,-1]
print("\nNew data points : \n", new_data)


Data : 
 [[ 8 24]
 [ 0  2]
 [ 7 18]
 [ 9 17]
 [ 2  2]]

Mean : 
 [[ 5.2 12.6]]

Covariance : 
 [[12.56 29.48]
 [29.48 80.64]]

Mean suubtracted data : 
 [[  2.8  11.4]
 [ -5.2 -10.6]
 [  1.8   5.4]
 [  3.8   4.4]
 [ -3.2 -10.6]]

Eigen values : 
 [ 1.56898846 91.63101154]

Eigen vectors : 
 [[-0.93699613  0.34933973]
 [-0.34933973 -0.93699613]]

New data points (centered) : 
 [[-11.65990716]
 [ 11.74872561]
 [ -5.68859063]
 [ -5.45027396]
 [ 11.05004614]]

New data points : 
 [[-25.28262503]
 [ -1.87399226]
 [-19.3113085 ]
 [-19.07299183]
 [ -2.57267173]]


## SVD

In [6]:
# # Add data
# data = np.matrix([[8, 24],[0 ,2],[7, 18],[9 ,17],[2, 2]])
# print("\nData : \n", data)

# n = data.shape[0]

# # Mean of data 
# mean = data.mean(axis = 0)
# print("\nMean : \n", mean )

# # Covariance of data 
# covar = np.cov(data.T)*(n-1)/n
# print("\nCovariance : \n", covar)

# # Mean subtracted data
# centered_data = data - data.mean(axis = 0)
# print("\nMean suubtracted data : \n", centered_data)

# For any random matrix 
mat1 = covar
mat1 = np.matrix([[3,2,2],[2,3,-2]])

# U, D, V - SVD
U, D, V = np.linalg.svd(mat1)
print("\nSVD Decomposition - \n")
print("\nU : \n", U)
print("\nD : \n", D)
print("\nV : \n", V)

# Calculate Left vector
print("\n\n Left Singular Matrix")
aaT = mat1 * mat1.T
print("\n Mat1.Mat1.T ", aaT)
eig_val_U, eig_vec_U = np.linalg.eig(aaT)
print("\n Eigen Values : \n", eig_val_U)
print("\n Eigen Vectors : \n", eig_vec_U)

# Calculate Right vector
print("\n\n Right Singular Matrix")
aTa = mat1.T * mat1
print("\n Mat1.T * Mat1 ", aTa)
eig_val_V, eig_vec_V = np.linalg.eig(aTa)
print("\n Eigen Values : \n", eig_val_V)
print("\n Eigen Vectors : \n", eig_vec_V)

# Sigma matrix
sigma = np.diag(np.sqrt(eig_val_U))
print("\nSigma : \n", sigma)


SVD Decomposition - 


U : 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

D : 
 [5. 3.]

V : 
 [[ 7.07106781e-01  7.07106781e-01  3.67439059e-16]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]


 Left Singular Matrix

 Mat1.Mat1.T  [[17  8]
 [ 8 17]]

 Eigen Values : 
 [25.  9.]

 Eigen Vectors : 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


 Right Singular Matrix

 Mat1.T * Mat1  [[13 12  2]
 [12 13 -2]
 [ 2 -2  8]]

 Eigen Values : 
 [2.50000000e+01 4.69538746e-15 9.00000000e+00]

 Eigen Vectors : 
 [[-7.07106781e-01 -6.66666667e-01  2.35702260e-01]
 [-7.07106781e-01  6.66666667e-01 -2.35702260e-01]
 [ 1.42731104e-17  3.33333333e-01  9.42809042e-01]]

Sigma : 
 [[5. 0.]
 [0. 3.]]


## Chi-square Independence test

In [7]:
# Data 
data = np.matrix([
[7,33,5],
[24,18,8],
[13,30,0],
[3,7,2]]
)

sum_data = np.sum(data)

expected_values = np.zeros(data.shape)
for i in range(data.shape[0]):
    for j in range(data.shape[1]):
        expected_values[i][j] = np.sum(data[:,j]) * np.sum(data[i,:]) / sum_data
    
chi_square_value = 0
for i in range(data.shape[0]):
    for j in range(data.shape[1]):
        chi_square_value += (np.power(data[i,j] - expected_values[i,j],2))/ expected_values[i,j]
        
Degree_of_Freedom = (data.shape[0]-1)*(data.shape[1]-1)

Significance_level = 0.05

# Find p_value(chi_square_value) from  table
# If p_value< significane_level, then reject null hypothesis

# max_possible_extreme_value = stats.chi2.ppf(1-.05, df=Degree_of_Freedom)

In [8]:
dir(stats.chi2)

['__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_argcheck',
 '_argcheck_rvs',
 '_attach_argparser_methods',
 '_attach_methods',
 '_cdf',
 '_cdf_single',
 '_cdfvec',
 '_construct_argparser',
 '_construct_default_doc',
 '_construct_doc',
 '_ctor_param',
 '_entropy',
 '_fit_loc_scale_support',
 '_fitstart',
 '_get_support',
 '_isf',
 '_logcdf',
 '_logpdf',
 '_logsf',
 '_mom0_sc',
 '_mom1_sc',
 '_mom_integ0',
 '_mom_integ1',
 '_moment_error',
 '_munp',
 '_nnlf',
 '_nnlf_and_penalty',
 '_open_support_mask',
 '_parse_arg_template',
 '_parse_args',
 '_parse_args_rvs',
 '_parse_args_stats',
 '_pdf',
 '_penalized_nnlf',
 '_ppf',
 

In [9]:
p_value = stats.chi2.pdf(chi_square_value,Degree_of_Freedom)

In [10]:
stats.chi2.ppf(0.0013, df=Degree_of_Freedom)

4.1778745093195613e-01

In [11]:
 stats.chi2.pdf(2.4706106836607007,6)

1.1091808276696606e-01

In [12]:
chi_square_value

21.799150647994043